spring:
  application:
    name: cat-home-pc
#    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_home_pc
    username: root
    password: 19980620WWW
#    上传文件大小配置
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


#mybatis配置信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云配置文件
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t9fuYJdq17jcAxuGfon
    accessKeySecret: XeDAdwJlSbsrZsqwJmQhnbKjcvHVsr
    bucketName: aiwebstudy

#事物管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#端口
server:
  port: 8080